### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by rwieruch** [the-road-to-learn-react/the-road-to-learn-react#96]
At the moment, there is a high likelihood that you run into the following error when building your Hacker News application.

`Failed to load https://hn.algolia.com/api/v1/search?query=foo&page=0&hitsPerPage=100: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I am checking back with Algolia if there is anything to fix it on our side of if there was any change on their side in the first place. https://github.com/algolia/hn-search/issues/106

If there is no solution to this in the long run, I have to change the API to a [different one](https://github.com/cheeaun/node-hnapi). Otherwise I think a backend proxy could be a solution. Even though I would love if students could still use the official HN API 😢  

In the meantime, you could try to replace your requests to Algolia with another API: https://github.com/cheeaun/node-hnapi There you have an up and running Hacker News API server (e.g. https://node-hnapi.herokuapp.com/news?page=3).

**Comment by rwieruch** [comment]
Fixed: https://github.com/algolia/hn-search/issues/106#issuecomment-352182060

**Comment by Kovner** [comment]
Are you sure this is fixed? I am getting the same error:

Failed to load https://hn.algolia.com/api/v1/searchquery=redux: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by rwieruch** [comment]
@Kovner I think your request misses a `?`. Can you try again `https://hn.algolia.com/api/v1/search?query=redux` ?

**Comment by Kovner** [comment]
Yep that was it sorry! That question got hidden in the template string variables!

**Comment by oscaralanpierce** [comment]
I am still getting this issue:
```

fetchSearchTopStories @ App.js:70
onSearchSubmit @ App.js:46
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:461
executeDispatchesInOrder @ react-dom.development.js:483
executeDispatchesAndRelease @ react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:592
forEachAccumulated @ react-dom.development.js:562
runEventsInBatch @ react-dom.development.js:723
runExtractedEventsInBatch @ react-dom.development.js:732
handleTopLevel @ react-dom.development.js:4477
batchedUpdates$1 @ react-dom.development.js:16660
batchedUpdates @ react-dom.development.js:2131
dispatchEvent @ react-dom.development.js:4556
interactiveUpdates$1 @ react-dom.development.js:16715
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4533
localhost/:1 Failed to load https://hn.algolia.com/api/v1/search?query=redux&page=%20%20%20%20%20%200&hitsPerPage=100: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3001' is therefore not allowed access. The response had HTTP status code 400. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
This is a screen cap of the Network tab in my browser (which is Chrome, if it matters):
![screen shot 2018-09-01 at 1 06 40 pm](https://user-images.githubusercontent.com/5115928/44949512-161fc980-ade8-11e8-9371-ed110e47d134.png)

This happened after I implemented the client cache, although I had taken a break for a week or two so maybe something changed in the HN API since then?

**Comment by oscaralanpierce** [comment]
Oh and also! Changing to the GitHub API did not help.

**Comment by rwieruch** [comment]
@danascheider can you share your project on GitHub?

**Comment by oscaralanpierce** [comment]
@rwieruch You bet! [Here it is!](https://github.com/danascheider/road-to-learn-react)

**Comment by rwieruch** [comment]
@danascheider see https://github.com/danascheider/road-to-learn-react/pull/1 You can simply merge the PR and everything should be fixed. Check the commits again to understand what has been wrong.

**Comment by angeldelacruzdev** [comment]
### My problem. 

`Failed to load http://127.0.0.1:8000/api/fileupload: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
createError.js:17 Uncaught (in promise) Error: Network Error
    at createError (createError.js:17)
    at XMLHttpRequest.handleError (xhr.js:87)`

**Comment by miloszpanas** [comment]
I'm having the very same issue when trying to fetch data from API

`Access to fetch at 'https://hn.algolia.com/api/v1/search?query=react' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Any ideas? Here's the repo: 
https://github.com/miloszpanas/react_practice

**Comment by rwieruch** [comment]
That's odd @miloszpanas I cloned https://github.com/the-road-to-learn-react/hackernews-client and it worked for me.

**Comment by miloszpanas** [comment]
> That's odd @miloszpanas I cloned https://github.com/the-road-to-learn-react/hackernews-client and it worked for me.

It's really weird, I couldn't get it to work yesterday, today it works just fine with no modifications on my part. No idea what was causing it. Sorry for bothering
